- name: update packages
  apt:
    update_cache: yes

- name: install dependencies
  apt:
    pkg: ['libssl-dev', 'libudev-dev', 'pkg-config', 'zlib1g-dev', 'llvm', 'clang', 'make', 'git']
    state: latest

- name: install linux kernel tools
  apt:
    pkg: ["linux-tools-generic", "linux-tools-{{ ansible_kernel }}"]
    state: latest

- name: install user tools
  apt:
    pkg: ["htop", "iotop", "powertop", "cpufrequtils", "iptraf-ng", "nload"]
    state: latest